-- ============================================================================
-- 0000_initial_schema.sql
-- DeepFlow (GB Electrical) — baseline schema for the `public` schema
-- ============================================================================
--
-- WHAT THIS FILE IS
--
-- This file is a from-scratch reconstruction of the ENTIRE current live
-- `public` schema of Supabase project `dzqyqpuhxdrrpipbehpk`, generated by
-- introspecting the live catalog directly (information_schema, pg_catalog,
-- pg_proc, pg_policies, pg_indexes, pg_publication_tables, pg_default_acl —
-- not approximated from docs, not reconstructed from memory) on 2026-08-11.
--
-- It exists to close a gap documented in full in
-- docs/architecture/07-sql-migrations.md §2 and §4, and
-- docs/planning/23-developer-onboarding.md §B2: every other file in this
-- `supabase/migrations/` folder is an ALTER TABLE / CREATE INDEX / CREATE
-- POLICY / CREATE OR REPLACE FUNCTION / DROP statement that assumes its
-- target already exists. None of them contain a CREATE TABLE. Replaying the
-- folder against a genuinely empty Supabase project fails immediately on the
-- first statement. This file is what those other files were always missing:
-- an actual bootstrap script.
--
-- HOW TO USE THIS FILE — READ THIS BEFORE APPLYING ANYTHING IN THIS FOLDER
--
--   * Standing up a brand-new, empty Supabase project at DeepFlow's CURRENT
--     schema state? Apply ONLY this file. It is self-sufficient — extensions,
--     sequences, tables, constraints, indexes, functions/RPCs, the one
--     trigger, RLS + every policy, default privileges, and the realtime
--     publication membership are all in here, already in their final,
--     current form.
--
--   * Do NOT then replay the other ~50 timestamped files in this folder
--     (20260718130728_... through 20260809010000_...) after this one. They
--     are this specific project's historical change log, not a second step
--     of a bootstrap sequence. Every change any of them ever made is already
--     reflected in this file in its final form. Replaying them after this
--     file would re-attempt already-applied ADD COLUMN / CREATE POLICY /
--     CREATE INDEX statements and fail with "already exists" errors (most
--     use IF NOT EXISTS / OR REPLACE / DROP...IF EXISTS guards so some would
--     silently no-op rather than error, but several — bare CREATE POLICY,
--     CREATE TABLE-less ALTER sequences — would not).
--
--   * Working against the existing live GB Electrical project
--     (`dzqyqpuhxdrrpipbehpk`)? You never need to apply this file at all —
--     the schema it describes already exists there. This file is for a
--     *second*, independent project only (see docs/planning/23-developer-
--     onboarding.md Part B — standing up a fresh instance for a new
--     company), or for disaster-recovery rebuild of this one.
--
--   * All future schema changes should still be written as new, individually
--     timestamped files in this folder per the existing convention
--     (docs/architecture/07-sql-migrations.md §5) — this file is a one-time
--     baseline capture, not a replacement for that convention.
--
-- WHAT THIS FILE DELIBERATELY DOES NOT COVER
--
--   * The `auth` schema itself (Supabase Auth's own tables) — provisioned by
--     Supabase automatically on every project, never DeepFlow's DDL. Two
--     things below DO reach into `auth`, both captured verbatim exactly as
--     they exist live: the `trg_auto_admin` trigger is defined ON
--     `auth.users`, and the `create_confirmed_user()` / `get_auth_users()`
--     functions read/write `auth.users`/`auth.identities` directly. Applying
--     this file requires a role with privileges on the `auth` schema (the
--     Supabase migration/CLI/MCP pathway already runs as such a role — see
--     docs/architecture/07-sql-migrations.md §5 for how migrations are
--     normally applied here).
--   * Storage: the app expects one bucket named `deepflow` (private, per
--     `20260808_make_deepflow_bucket_private.sql`) plus a set of
--     `storage.objects`/`storage.buckets` RLS policies — none of that is
--     `public`-schema DDL and none of it is captured here. See
--     docs/planning/23-developer-onboarding.md §B3 for what a fresh
--     instance needs on the Storage side.
--   * Edge Functions (`supabase/functions/*`) — deployed separately, not
--     part of this or any SQL migration.
--   * Any row data. This is schema only. The live project's data was fully
--     reset on 2026-08-06; every table is empty except `app_settings` (1
--     row) and `users` (1 row) — see docs/architecture/05-database.md §1.
--
-- ============================================================================


-- ============================================================================
-- SECTION 1 — EXTENSIONS
-- ============================================================================
-- Confirmed live via list_extensions: pgcrypto and uuid-ossp are installed
-- in the `extensions` schema, pg_stat_statements likewise. A genuinely fresh
-- Supabase project ships with `extensions` schema already present but these
-- specific extensions NOT yet enabled — IF NOT EXISTS makes this file safe
-- to apply either way.

CREATE EXTENSION IF NOT EXISTS pgcrypto WITH SCHEMA extensions;
CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA extensions;
CREATE EXTENSION IF NOT EXISTS pg_stat_statements WITH SCHEMA extensions;


-- ============================================================================
-- SECTION 2 — SEQUENCES
-- ============================================================================
-- Six standalone sequences back the next_*_num()/portal_next_request_ref()
-- RPCs below (packages/business human-readable reference numbers: job
-- numbers, invoice numbers, credit-note numbers, agency numbers, proforma
-- numbers, portal client-request references). `invoice_audit.id` and
-- `push_subscriptions.id` are separate, identity-column-owned sequences —
-- those are declared inline on the table (GENERATED ALWAYS AS IDENTITY) in
-- Section 3, not here.
--
-- START WITH below matches each sequence's originally configured start
-- value (pg_sequences.start_value), not its current position — at the time
-- this file was generated, live `last_value`s had already advanced past
-- these (e.g. job_num_seq's last_value was 1063, inv_num_seq's was 2033)
-- because sequence position is data-like runtime state, not schema, and
-- wasn't part of the 2026-08-06 table-data reset. A fresh project starts
-- numbering from the same baseline GB Electrical's live project originally
-- did; it will not collide with production because it's a separate project.

CREATE SEQUENCE IF NOT EXISTS public.job_num_seq START WITH 1014 INCREMENT BY 1 MINVALUE 1 NO CYCLE;
CREATE SEQUENCE IF NOT EXISTS public.job_cr_seq START WITH 5 INCREMENT BY 1 MINVALUE 1 NO CYCLE;
CREATE SEQUENCE IF NOT EXISTS public.inv_num_seq START WITH 1998 INCREMENT BY 1 MINVALUE 1 NO CYCLE;
CREATE SEQUENCE IF NOT EXISTS public.agn_num_seq START WITH 2001 INCREMENT BY 1 MINVALUE 1 NO CYCLE;
CREATE SEQUENCE IF NOT EXISTS public.proforma_num_seq START WITH 1 INCREMENT BY 1 MINVALUE 1 NO CYCLE;
CREATE SEQUENCE IF NOT EXISTS public.portal_request_seq START WITH 2 INCREMENT BY 1 MINVALUE 1 NO CYCLE;


-- ============================================================================
-- SECTION 3 — TABLES
-- ============================================================================
-- Created in dependency order (referenced tables before referrers). Foreign
-- key constraints themselves are added afterward in Section 4, once every
-- table exists — this avoids forward-reference ordering problems entirely.
-- The one CHECK constraint that calls a function (invoices.items ->
-- valid_invoice_items()) is likewise added in Section 6, after that
-- function is created in Section 5, for the same reason.

-- ---------------------------------------------------------------------------
-- 3.1 persons — the Directory: landlords / individual clients
-- ---------------------------------------------------------------------------
CREATE TABLE public.persons (
  id                      text PRIMARY KEY,
  name                    text NOT NULL,
  phone                   text,
  email                   text,
  wa                      text,
  address                 text,
  notes                   text,
  roles                   jsonb DEFAULT '[]'::jsonb,
  rate                    numeric,
  created                 bigint,
  modified                bigint,
  portal_token            uuid DEFAULT gen_random_uuid(),
  portal_enabled          boolean DEFAULT false,
  last_portal_access      timestamptz,
  bankname                text,
  bankacc                 text,
  banksort                text,
  bankref                 text,
  agencyid                text,
  trade                   text,
  hourly_rate             numeric DEFAULT 0,
  default_trade           text,
  whatsapp                text,
  portal_pin_hash         text,
  portal_pin_fail_count   integer NOT NULL DEFAULT 0,
  portal_pin_locked_until timestamptz,
  archived                boolean NOT NULL DEFAULT false
);

-- ---------------------------------------------------------------------------
-- 3.2 agencies — the Directory: letting agencies
-- ---------------------------------------------------------------------------
CREATE TABLE public.agencies (
  id                      text PRIMARY KEY,
  name                    text NOT NULL,
  phone                   text,
  email                   text,
  wa                      text,
  address                 text,
  website                 text,
  notes                   text,
  portal_token            text UNIQUE DEFAULT encode(extensions.gen_random_bytes(12), 'hex'::text),
  created                 bigint,
  modified                bigint,
  portal_enabled          boolean DEFAULT false,
  last_portal_access      timestamptz,
  bankname                text,
  bankacc                 text,
  banksort                text,
  bankref                 text,
  portal_pin_hash         text,
  portal_pin_fail_count   integer NOT NULL DEFAULT 0,
  portal_pin_locked_until timestamptz
);

-- ---------------------------------------------------------------------------
-- 3.3 agents — the Directory: individual agents at an agency
-- ---------------------------------------------------------------------------
CREATE TABLE public.agents (
  id                      text PRIMARY KEY,
  name                    text NOT NULL,
  phone                   text,
  email                   text,
  wa                      text,
  title                   text,
  notes                   text,
  agencyid                text,
  created                 bigint,
  modified                bigint,
  portal_pin_hash         text,
  portal_pin_fail_count   integer NOT NULL DEFAULT 0,
  portal_pin_locked_until timestamptz
);

-- ---------------------------------------------------------------------------
-- 3.4 jobs — the central work-order record
-- ---------------------------------------------------------------------------
CREATE TABLE public.jobs (
  id                  text PRIMARY KEY,
  jobnum              text,
  date                text,
  address             text NOT NULL,
  referrer            text,
  trade               text,
  certtypes           jsonb DEFAULT '[]'::jsonb,
  engineer            text,
  description         text,
  timeslot            text,
  access              text,
  contact             text,
  price               numeric DEFAULT 0,
  notes               text,
  priority            text DEFAULT 'Normal'::text,
  status              text DEFAULT 'Pending'::text,
  landlordname        text,
  landlordphone       text,
  landlordemail       text,
  landlordaddr        text,
  landlordwa          text,
  landlordnotes       text,
  agencyname          text,
  agencyphone         text,
  agencyemail         text,
  agencynotes         text,
  agentname           text,
  agentphone          text,
  agentemail          text,
  portal_token        text UNIQUE DEFAULT encode(extensions.gen_random_bytes(12), 'hex'::text),
  created             bigint,
  modified            bigint,
  invnumber           text,
  linkedinvid         text,
  sortorder           integer,
  client_person_id    text,
  client_agency_id    text,
  checkin_time        timestamptz,
  checkout_time       timestamptz,
  checkin_location    text,
  engineer_signature  text,
  client_signature    text,
  invoice_id          uuid,
  agencyaddr          text,
  agencyaddress       text,
  confirmed           boolean DEFAULT true,
  postcode            text
);

-- ---------------------------------------------------------------------------
-- 3.5 certs — compliance certificates
-- ---------------------------------------------------------------------------
CREATE TABLE public.certs (
  id            text PRIMARY KEY,
  address       text,
  type          text,
  landlord      text,
  issuedate     text,
  expirydate    text,
  certnum       text,
  jobid         text,
  jobnum        text,
  engineer      text,
  notes         text,
  noexpiry      boolean DEFAULT false,
  created       bigint,
  pdf_url       text,
  pdf_path      text,
  agent         text,
  email         text,
  phone         text,
  notresponding boolean,
  appliances    jsonb DEFAULT '[]'::jsonb
);

-- ---------------------------------------------------------------------------
-- 3.6 invoices — every kind of billing document
-- ---------------------------------------------------------------------------
-- NOTE: the `valid_invoice_items(items)` CHECK constraint is added in
-- Section 6, after that function exists (Section 5) — see the file-level
-- note at the top of Section 3.
CREATE TABLE public.invoices (
  id                text PRIMARY KEY,
  number            text,
  clientid          text,
  clientname        text,
  clientemail       text,
  clientaddr        text,
  clientwa          text,
  date              text,
  duedate           text,
  description       text,
  jobid             text,
  items             jsonb DEFAULT '[]'::jsonb,
  status            text DEFAULT 'Draft'::text,
  created           bigint,
  agentcc           text,
  linkedjobid       text,
  jobref            text,
  terms             text,
  notes             text,
  client_person_id  text,
  client_agency_id  text,
  subtotal          numeric DEFAULT 0,
  vat_rate          numeric DEFAULT 20.00
                      CONSTRAINT invoices_vat_rate_sane_range
                      CHECK (vat_rate IS NULL OR (vat_rate >= 0::numeric AND vat_rate <= 100::numeric)),
  vat_amount        numeric DEFAULT 0,
  total             numeric DEFAULT 0,
  paid_amount       numeric DEFAULT 0,
  pdf_url           text,
  modified          timestamptz DEFAULT now(),
  isagency          boolean DEFAULT false,
  agencyaddress     text,
  landlordname      text,
  propertyaddress   text,
  jobnum            text,
  agentname         text,
  agentemail        text,
  agencyname        text,
  billtoname        text,
  billtoaddress     text,
  jobaddress        text,
  invoicetype       text DEFAULT 'landlord'::text,
  type              text,
  linkedinvid       text,
  reason            text,
  certtypes         text,
  jobdate           text,
  engineer          text,
  bill_to_override  boolean NOT NULL DEFAULT false,
  pdf_path          text
);

COMMENT ON COLUMN public.invoices.bill_to_override IS
  'When true, billtoname/billtoaddress on this invoice are a display-only override and must not be synced back to jobs.landlordname or the persons/agencies table.';

-- ---------------------------------------------------------------------------
-- 3.7 job_comments — internal, office-only notes thread on a job
-- ---------------------------------------------------------------------------
CREATE TABLE public.job_comments (
  id      text PRIMARY KEY,
  jobid   text,
  author  text,
  message text,
  ts      bigint DEFAULT (EXTRACT(epoch FROM now()) * (1000)::numeric)
);

-- ---------------------------------------------------------------------------
-- 3.8 attachments — index card for files held in Supabase Storage
-- ---------------------------------------------------------------------------
CREATE TABLE public.attachments (
  id                text PRIMARY KEY,
  jobid             text,
  name              text,
  type              text,
  mime              text,
  storage_path      text,
  url               text,
  uploaded_by_name  text,
  created           bigint DEFAULT (EXTRACT(epoch FROM now()) * (1000)::numeric),
  photo_slot        integer,
  photo_role        text
);

-- ---------------------------------------------------------------------------
-- 3.9 users — login accounts (office staff and field engineers share this)
-- ---------------------------------------------------------------------------
CREATE TABLE public.users (
  id                  text PRIMARY KEY,
  name                text NOT NULL,
  email               text,
  role                text DEFAULT 'engineer'::text,
  phone               text,
  active              boolean DEFAULT true,
  created             bigint DEFAULT (EXTRACT(epoch FROM now()) * (1000)::numeric),
  last_lat            double precision,
  last_lng            double precision,
  last_seen           bigint,
  last_accuracy       integer,
  auth_id             uuid,
  can_edit            boolean DEFAULT true,
  can_delete          boolean DEFAULT false,
  can_invoice         boolean DEFAULT true,
  can_finance         boolean DEFAULT false,
  see_landlord        boolean DEFAULT true,
  see_landlord_phone  boolean DEFAULT true,
  see_agent           boolean DEFAULT true,
  see_contact         boolean DEFAULT true,
  see_price           boolean DEFAULT false,
  internal_email      text,
  session_token       text,
  session_expires     bigint,
  is_protected        boolean DEFAULT false,
  pin_hash            text,
  pin_fail_count      integer NOT NULL DEFAULT 0,
  pin_locked_until    timestamptz,
  pin_reset_allowed   boolean NOT NULL DEFAULT false
);

-- ---------------------------------------------------------------------------
-- 3.10 activity — broad, one-way "what just happened" feed
-- ---------------------------------------------------------------------------
CREATE TABLE public.activity (
  id      text PRIMARY KEY,
  msg     text,
  type    text,
  ts      bigint DEFAULT (EXTRACT(epoch FROM now()) * (1000)::numeric),
  created timestamp without time zone DEFAULT now()
);

-- ---------------------------------------------------------------------------
-- 3.11 engineer_requests — shared inbox: engineer overtime/leave + portal
--      "please book a job" client requests (told apart by `type`)
-- ---------------------------------------------------------------------------
CREATE TABLE public.engineer_requests (
  id            text PRIMARY KEY,
  engineer_name text NOT NULL,
  type          text NOT NULL,
  date          text,
  hours         numeric,
  rate          text,
  job           text,
  leave_type    text,
  leave_from    text,
  leave_to      text,
  notes         text,
  status        text DEFAULT 'pending'::text,
  office_reply  text,
  created       bigint DEFAULT (EXTRACT(epoch FROM now()) * (1000)::numeric)
);

-- ---------------------------------------------------------------------------
-- 3.12 engineer_alerts — office-to-engineer broadcast messages
-- ---------------------------------------------------------------------------
CREATE TABLE public.engineer_alerts (
  id      uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  target  text DEFAULT 'all'::text,
  type    text DEFAULT 'info'::text,
  title   text,
  message text,
  sent_by text,
  created bigint,
  expires bigint,
  status  text DEFAULT 'active'::text
);

-- ---------------------------------------------------------------------------
-- 3.13 app_settings — single-row (key='__all__') JSON configuration store
-- ---------------------------------------------------------------------------
CREATE TABLE public.app_settings (
  key     text PRIMARY KEY,
  value   text NOT NULL,
  updated bigint DEFAULT 0
);

-- ---------------------------------------------------------------------------
-- 3.14 payments — one row per payment recorded against an invoice
-- ---------------------------------------------------------------------------
CREATE TABLE public.payments (
  id            text PRIMARY KEY,
  inv_id        text NOT NULL,
  date          text,
  amount        numeric NOT NULL DEFAULT 0,
  method        text DEFAULT 'Bank Transfer'::text,
  ref           text,
  recorded_by   text,
  created       bigint,
  notes         text
);

-- ---------------------------------------------------------------------------
-- 3.15 cert_reminder_log — dedup log: one row per expiry reminder sent
-- ---------------------------------------------------------------------------
CREATE TABLE public.cert_reminder_log (
  id          text PRIMARY KEY DEFAULT (gen_random_uuid())::text,
  cert_id     text NOT NULL,
  sent_at     timestamptz NOT NULL DEFAULT now(),
  days_before integer,
  method      text DEFAULT 'whatsapp'::text
);

-- ---------------------------------------------------------------------------
-- 3.16 expenses — engineer-facing cost tracking
-- ---------------------------------------------------------------------------
CREATE TABLE public.expenses (
  id          text PRIMARY KEY,
  date        text,
  engineer    text,
  category    text,
  description text,
  cost        numeric DEFAULT 0,
  receipt     text,
  created     bigint,
  jobref      text,
  modified    bigint
);

-- ---------------------------------------------------------------------------
-- 3.17 overtime — engineer overtime/absence hours (payroll deductions use
--      deliberately negative `hours`)
-- ---------------------------------------------------------------------------
CREATE TABLE public.overtime (
  id       text PRIMARY KEY,
  engineer text,
  date     text,
  type     text,
  hours    numeric DEFAULT 0,
  label    text,
  notes    text,
  created  bigint
);

-- ---------------------------------------------------------------------------
-- 3.18 audit_log — strict, narrow, Admin-only sensitive-event trail
-- ---------------------------------------------------------------------------
CREATE TABLE public.audit_log (
  id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  type        text,
  staff_name  text,
  staff_email text,
  staff_role  text,
  details     jsonb,
  created_at  timestamptz DEFAULT now()
);

-- ---------------------------------------------------------------------------
-- 3.19 portal_contacts — manually-curated "who to contact" list shown in
--      the Client Portal
-- ---------------------------------------------------------------------------
CREATE TABLE public.portal_contacts (
  id           text PRIMARY KEY,
  label        text,
  contact_name text,
  phone        text,
  sort_order   integer DEFAULT 0,
  created      timestamptz DEFAULT now()
);

-- ---------------------------------------------------------------------------
-- 3.20 invoice_audit — per-invoice audit trail (created/sent/failed/
--      converted events). Column names quoted where they are camelCase or
--      reserved words ("invoiceId", "from", "to", "user"), matching live.
-- ---------------------------------------------------------------------------
CREATE TABLE public.invoice_audit (
  id          bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  "invoiceId" text NOT NULL,
  action      text,
  details     text,
  "from"      text,
  "to"        text,
  "user"      text,
  timestamp   bigint
);

-- ---------------------------------------------------------------------------
-- 3.21 push_subscriptions — Web Push subscription storage (staff + portal
--      client subscriptions; entity_table/entity_id identify the owner)
-- ---------------------------------------------------------------------------
CREATE TABLE public.push_subscriptions (
  id            bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  entity_table  text NOT NULL,
  entity_id     text NOT NULL,
  endpoint      text NOT NULL UNIQUE,
  p256dh        text NOT NULL,
  auth          text NOT NULL,
  created_at    timestamptz NOT NULL DEFAULT now()
);


-- ============================================================================
-- SECTION 4 — FOREIGN KEYS
-- ============================================================================
-- Exactly nine, all confirmed live via information_schema.referential_
-- constraints. Five are original/long-standing (agents/attachments/certs/
-- invoices/job_comments -> jobs or agencies); four are the newest addition,
-- from 20260809010000_fix_client_id_type_mismatch_add_real_fks.sql, which
-- changed jobs/invoices.client_person_id/client_agency_id from a type-
-- mismatched uuid (that could never really be a FK against persons.id/
-- agencies.id, both `text`) to `text`, then added the real constraints below.
-- ON DELETE SET NULL (not RESTRICT/CASCADE) on every Directory-pointing FK
-- is deliberate: removing a person/agency/job should never be blocked by,
-- or cascade-delete, linked history.

ALTER TABLE public.agents
  ADD CONSTRAINT agents_agencyid_fkey FOREIGN KEY (agencyid) REFERENCES public.agencies(id) ON DELETE SET NULL;

ALTER TABLE public.attachments
  ADD CONSTRAINT attachments_jobid_fkey FOREIGN KEY (jobid) REFERENCES public.jobs(id) ON DELETE CASCADE;

ALTER TABLE public.certs
  ADD CONSTRAINT certs_jobid_fkey FOREIGN KEY (jobid) REFERENCES public.jobs(id) ON DELETE SET NULL;

ALTER TABLE public.invoices
  ADD CONSTRAINT invoices_jobid_fkey FOREIGN KEY (jobid) REFERENCES public.jobs(id) ON DELETE SET NULL;

ALTER TABLE public.job_comments
  ADD CONSTRAINT job_comments_jobid_fkey FOREIGN KEY (jobid) REFERENCES public.jobs(id) ON DELETE CASCADE;

ALTER TABLE public.jobs
  ADD CONSTRAINT jobs_client_person_id_fkey FOREIGN KEY (client_person_id) REFERENCES public.persons(id) ON DELETE SET NULL;

ALTER TABLE public.jobs
  ADD CONSTRAINT jobs_client_agency_id_fkey FOREIGN KEY (client_agency_id) REFERENCES public.agencies(id) ON DELETE SET NULL;

ALTER TABLE public.invoices
  ADD CONSTRAINT invoices_client_person_id_fkey FOREIGN KEY (client_person_id) REFERENCES public.persons(id) ON DELETE SET NULL;

ALTER TABLE public.invoices
  ADD CONSTRAINT invoices_client_agency_id_fkey FOREIGN KEY (client_agency_id) REFERENCES public.agencies(id) ON DELETE SET NULL;


-- ============================================================================
-- SECTION 5 — INDEXES
-- ============================================================================
-- Only indexes NOT already implied by a PRIMARY KEY/UNIQUE constraint
-- declared in Section 3. Every definition below is transcribed verbatim
-- from live `pg_indexes.indexdef`.

CREATE INDEX idx_agents_agencyid ON public.agents USING btree (agencyid);

CREATE INDEX idx_attachments_jobid ON public.attachments USING btree (jobid);

CREATE INDEX idx_certs_expiry ON public.certs USING btree (expirydate);
CREATE INDEX idx_certs_jobid ON public.certs USING btree (jobid);

CREATE INDEX idx_invoices_jobid ON public.invoices USING btree (jobid);

CREATE INDEX idx_job_comments_jobid ON public.job_comments USING btree (jobid);

CREATE INDEX idx_jobs_client_agency ON public.jobs USING btree (client_agency_id);
CREATE INDEX idx_jobs_client_person ON public.jobs USING btree (client_person_id);
CREATE INDEX idx_jobs_date ON public.jobs USING btree (date);
CREATE INDEX idx_jobs_engineer ON public.jobs USING btree (engineer);
CREATE INDEX idx_jobs_invoice ON public.jobs USING btree (invoice_id);
CREATE INDEX idx_jobs_portal ON public.jobs USING btree (portal_token);
CREATE INDEX idx_jobs_status ON public.jobs USING btree (status);
CREATE INDEX jobs_postcode_idx ON public.jobs USING btree (postcode);

-- Unique (not a named table constraint — index-only uniqueness, matches live)
CREATE UNIQUE INDEX idx_persons_portal_token ON public.persons USING btree (portal_token);

CREATE INDEX push_subscriptions_entity_idx ON public.push_subscriptions USING btree (entity_table, entity_id);

CREATE INDEX idx_users_auth_id ON public.users USING btree (auth_id);
CREATE INDEX idx_users_email ON public.users USING btree (email);
CREATE INDEX idx_users_role ON public.users USING btree (role);
CREATE INDEX idx_users_session_token ON public.users USING btree (session_token);
-- Partial unique index: only enforces uniqueness where phone is actually set
CREATE UNIQUE INDEX users_phone_unique ON public.users USING btree (phone) WHERE (phone IS NOT NULL);

CREATE INDEX invoice_audit_invoiceid_idx ON public.invoice_audit USING btree ("invoiceId");


-- ============================================================================
-- SECTION 6 — FUNCTIONS / RPCs
-- ============================================================================
-- All 41 functions in the `public` schema, transcribed verbatim via
-- pg_get_functiondef(oid) — bodies, SET search_path, SECURITY DEFINER/
-- volatility markers, and default arguments are exactly what's live, not
-- reconstructed. Grouped alphabetically (the order they were fetched in),
-- which is safe: no SQL-language function here calls another public
-- function (only tables/sequences/auth.uid(), all already created above),
-- and plpgsql function bodies aren't validated against referenced-object
-- existence at CREATE time, only at call time — so there is no forward-
-- reference ordering hazard among these 41 regardless of the order below.
--
-- One function is knowingly captured "broken", on purpose: verify_engineer_
-- login() (near the end of this section) references `v_user.pin`, a column
-- that no longer exists on `users` (superseded by pin_hash/pin_fail_count/
-- pin_locked_until/pin_reset_allowed). It would raise "column pin does not
-- exist" if actually invoked. It is captured byte-for-byte anyway because
-- that is what is genuinely live — its EXECUTE grant was already revoked
-- from anon/authenticated by 20260725163831_h1_revoke_dead_verify_engineer_
-- login_rpc.sql, so it is unreachable via the API today; see Section 8.

CREATE OR REPLACE FUNCTION public.admin_set_seq(seq_name text, new_start integer)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
BEGIN
  IF seq_name NOT IN ('job_num_seq','job_cr_seq','inv_num_seq','agn_num_seq','proforma_num_seq') THEN
    RAISE EXCEPTION 'Invalid sequence name: %', seq_name;
  END IF;
  EXECUTE format('ALTER SEQUENCE %I RESTART WITH %s', seq_name, GREATEST(new_start, 1));
END;
$function$;

CREATE OR REPLACE FUNCTION public.auto_create_admin_profile()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
BEGIN
  IF lower(NEW.email) = 'mandeepdynamics@gmail.com' THEN
    INSERT INTO users (
      id, name, email, auth_id, role, active,
      can_edit, can_delete, can_invoice, can_finance,
      see_landlord, see_landlord_phone, see_agent, see_contact, see_price,
      created
    ) VALUES (
      gen_random_uuid(),
      'Admin',
      'mandeepdynamics@gmail.com',
      NEW.id,
      'admin',
      true,
      true, true, true, true,
      true, true, true, true, true,
      extract(epoch from now())::bigint
    )
    ON CONFLICT DO NOTHING;
  END IF;
  RETURN NEW;
END;
$function$;

CREATE OR REPLACE FUNCTION public.check_cert_reminder_setup()
 RETURNS TABLE(step text, done boolean, detail text)
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
BEGIN
  -- Step 2: table
  RETURN QUERY SELECT 'table'::text,
    EXISTS(SELECT 1 FROM information_schema.tables WHERE table_schema='public' AND table_name='cert_reminder_log'),
    'cert_reminder_log table'::text;

  -- Step 3: function
  RETURN QUERY SELECT 'function'::text,
    EXISTS(SELECT 1 FROM pg_proc p JOIN pg_namespace n ON p.pronamespace=n.oid
           WHERE n.nspname='public' AND p.proname='send_cert_reminders'),
    'send_cert_reminders() function'::text;

  -- Step 4: cron schedule — requires the pg_cron extension itself to be
  -- enabled (Database → Extensions in the dashboard, can't be done from
  -- SQL alone). If it isn't enabled yet, cron.job doesn't exist at all —
  -- catch that specific case and report it plainly instead of erroring.
  BEGIN
    RETURN QUERY SELECT 'cron'::text,
      EXISTS(SELECT 1 FROM cron.job WHERE jobname='deepflow-cert-reminders'),
      'daily 9am schedule'::text;
  EXCEPTION WHEN undefined_table OR insufficient_privilege THEN
    RETURN QUERY SELECT 'cron'::text, false,
      'pg_cron extension not enabled yet (Database → Extensions)'::text;
  END;
END;
$function$;

CREATE OR REPLACE FUNCTION public.create_confirmed_user(p_email text, p_password text)
 RETURNS uuid
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'auth', 'public'
AS $function$
DECLARE v_user_id uuid; v_encrypted_pw text;
BEGIN
  v_user_id := gen_random_uuid();
  v_encrypted_pw := crypt(p_password, gen_salt('bf'));
  INSERT INTO auth.users (instance_id,id,aud,role,email,encrypted_password,
    email_confirmed_at,recovery_sent_at,last_sign_in_at,raw_app_meta_data,
    raw_user_meta_data,created_at,updated_at,confirmation_token,email_change,
    email_change_token_new,recovery_token)
  VALUES ('00000000-0000-0000-0000-000000000000',v_user_id,'authenticated',
    'authenticated',p_email,v_encrypted_pw,now(),now(),now(),
    '{"provider":"email","providers":["email"]}','{}',now(),now(),'','','','');
  INSERT INTO auth.identities (id,user_id,provider_id,identity_data,provider,
    last_sign_in_at,created_at,updated_at)
  VALUES (gen_random_uuid(),v_user_id,p_email,
    json_build_object('sub',v_user_id::text,'email',p_email),'email',now(),now(),now());
  RETURN v_user_id;
END; $function$;

CREATE OR REPLACE FUNCTION public.engineer_allow_pin_reset(p_id text, p_allow boolean)
 RETURNS boolean
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
BEGIN
  IF NOT is_office() THEN
    RAISE EXCEPTION 'Not authorized';
  END IF;
  UPDATE users SET pin_reset_allowed = p_allow
  WHERE id = p_id AND role = 'engineer';
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Engineer not found';
  END IF;
  RETURN true;
END;
$function$;

CREATE OR REPLACE FUNCTION public.engineer_pin_clear(p_id text, p_allow_reset boolean DEFAULT true)
 RETURNS boolean
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
BEGIN
  IF NOT is_office() THEN
    RAISE EXCEPTION 'Not authorized';
  END IF;
  UPDATE users SET pin_hash = NULL, session_token = NULL, session_expires = NULL,
    pin_fail_count = 0, pin_locked_until = NULL, pin_reset_allowed = p_allow_reset
  WHERE id = p_id AND role = 'engineer';
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Engineer not found';
  END IF;
  RETURN true;
END;
$function$;

CREATE OR REPLACE FUNCTION public.engineer_pin_login(p_phone text, p_pin text)
 RETURNS TABLE(ok boolean, session_token text, session_expires bigint, eng_id text, eng_name text, error_msg text, needs_setup boolean)
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public', 'extensions'
AS $function$
DECLARE
  rec record;
  new_token text;
  new_expires bigint;
  fails int;
BEGIN
  SELECT * INTO rec FROM users
  WHERE phone = p_phone AND role = 'engineer' AND active = true;

  IF NOT FOUND THEN
    RETURN QUERY SELECT false, NULL::text, NULL::bigint, NULL::text, NULL::text, 'Invalid phone or PIN'::text, false;
    RETURN;
  END IF;

  IF rec.pin_hash IS NULL THEN
    IF rec.pin_reset_allowed THEN
      RETURN QUERY SELECT false, NULL::text, NULL::bigint, rec.id, rec.name, 'Set up your PIN to continue'::text, true;
    ELSE
      RETURN QUERY SELECT false, NULL::text, NULL::bigint, NULL::text, NULL::text, 'Not authorised to log in — ask your office to grant you access'::text, false;
    END IF;
    RETURN;
  END IF;

  IF rec.pin_locked_until IS NOT NULL AND rec.pin_locked_until > now() THEN
    RETURN QUERY SELECT false, NULL::text, NULL::bigint, NULL::text, NULL::text, 'Too many attempts — try again later'::text, false;
    RETURN;
  END IF;

  IF p_pin !~ '^[0-9]{6}$' THEN
    RETURN QUERY SELECT false, NULL::text, NULL::bigint, NULL::text, NULL::text, 'Invalid phone or PIN'::text, false;
    RETURN;
  END IF;

  IF crypt(p_pin, rec.pin_hash) <> rec.pin_hash THEN
    fails := COALESCE(rec.pin_fail_count,0) + 1;
    IF fails >= 5 THEN
      UPDATE users SET pin_fail_count = fails, pin_locked_until = now() + interval '15 minutes' WHERE users.id = rec.id;
    ELSE
      UPDATE users SET pin_fail_count = fails WHERE users.id = rec.id;
    END IF;
    RETURN QUERY SELECT false, NULL::text, NULL::bigint, NULL::text, NULL::text, 'Invalid phone or PIN'::text, false;
    RETURN;
  END IF;

  new_token := encode(gen_random_bytes(32), 'hex');
  new_expires := extract(epoch FROM now())::bigint + 90*24*60*60;

  UPDATE users SET session_token = new_token, session_expires = new_expires,
    pin_fail_count = 0, pin_locked_until = NULL, last_seen = extract(epoch from now())::bigint
  WHERE users.id = rec.id;

  RETURN QUERY SELECT true, new_token, new_expires, rec.id, rec.name, NULL::text, false;
END;
$function$;

CREATE OR REPLACE FUNCTION public.engineer_pin_self_setup(p_phone text, p_new_pin text)
 RETURNS TABLE(ok boolean, session_token text, session_expires bigint, eng_id text, eng_name text, error_msg text)
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public', 'extensions'
AS $function$
DECLARE
  rec record;
  new_token text;
  new_expires bigint;
BEGIN
  IF p_new_pin !~ '^[0-9]{6}$' THEN
    RETURN QUERY SELECT false, NULL::text, NULL::bigint, NULL::text, NULL::text, 'PIN must be exactly 6 digits'::text;
    RETURN;
  END IF;

  SELECT * INTO rec FROM users
  WHERE phone = p_phone AND role = 'engineer' AND active = true;

  IF NOT FOUND OR rec.pin_hash IS NOT NULL OR NOT rec.pin_reset_allowed THEN
    RETURN QUERY SELECT false, NULL::text, NULL::bigint, NULL::text, NULL::text, 'Not authorised to set a PIN right now'::text;
    RETURN;
  END IF;

  new_token := encode(gen_random_bytes(32), 'hex');
  new_expires := extract(epoch FROM now())::bigint + 90*24*60*60;

  UPDATE users SET pin_hash = crypt(p_new_pin, gen_salt('bf')), pin_reset_allowed = false,
    session_token = new_token, session_expires = new_expires,
    pin_fail_count = 0, pin_locked_until = NULL, last_seen = extract(epoch from now())::bigint
  WHERE users.id = rec.id;

  RETURN QUERY SELECT true, new_token, new_expires, rec.id, rec.name, NULL::text;
END;
$function$;

CREATE OR REPLACE FUNCTION public.engineer_pin_set(p_id text, p_pin text)
 RETURNS boolean
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public', 'extensions'
AS $function$
BEGIN
  IF NOT is_office() THEN
    RAISE EXCEPTION 'Not authorized';
  END IF;
  IF p_pin !~ '^[0-9]{6}$' THEN
    RAISE EXCEPTION 'PIN must be exactly 6 digits';
  END IF;
  UPDATE users SET pin_hash = crypt(p_pin, gen_salt('bf')), pin_fail_count = 0, pin_locked_until = NULL,
    session_token = NULL, session_expires = NULL
  WHERE id = p_id AND role = 'engineer';
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Engineer not found';
  END IF;
  RETURN true;
END;
$function$;

CREATE OR REPLACE FUNCTION public.engineer_session_logout(p_id text, p_token text)
 RETURNS boolean
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
BEGIN
  UPDATE users SET session_token = NULL, session_expires = NULL
  WHERE id = p_id AND session_token = p_token AND role = 'engineer';
  RETURN true;
END;
$function$;

CREATE OR REPLACE FUNCTION public.get_auth_users()
 RETURNS TABLE(id uuid, email text, created_at timestamp with time zone)
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'auth', 'public'
AS $function$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM public.users WHERE auth_id = auth.uid() AND lower(role) = 'admin' AND active = true
  ) THEN
    RAISE EXCEPTION 'Not authorized';
  END IF;
  RETURN QUERY SELECT u.id, u.email::text, u.created_at FROM auth.users u ORDER BY u.created_at DESC;
END;
$function$;

CREATE OR REPLACE FUNCTION public.is_engineer()
 RETURNS boolean
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  SELECT EXISTS (
    SELECT 1 FROM users
    WHERE auth_id = auth.uid() AND role = 'engineer' AND active = true
  );
$function$;

CREATE OR REPLACE FUNCTION public.is_office()
 RETURNS boolean
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  SELECT EXISTS (
    SELECT 1 FROM users
    WHERE auth_id = auth.uid() AND role != 'engineer' AND active = true
  );
$function$;

CREATE OR REPLACE FUNCTION public.is_valid_engineer_token()
 RETURNS boolean
 LANGUAGE plpgsql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE v_token text; v_count int;
BEGIN
  BEGIN
    v_token := current_setting('request.headers', true)::json->>'x-engineer-token';
  EXCEPTION WHEN OTHERS THEN RETURN false; END;
  IF v_token IS NULL OR v_token = '' THEN RETURN false; END IF;
  SELECT count(*) INTO v_count FROM users
  WHERE session_token = v_token
    AND role = 'engineer'
    AND active = true
    AND session_expires > extract(epoch from now())::bigint;
  RETURN v_count > 0;
END;
$function$;

CREATE OR REPLACE FUNCTION public.my_engineer_name()
 RETURNS text
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  SELECT name FROM users
  WHERE auth_id = auth.uid() AND role = 'engineer' AND active = true
  LIMIT 1;
$function$;

CREATE OR REPLACE FUNCTION public.my_token_engineer_name()
 RETURNS text
 LANGUAGE plpgsql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE v_token text; v_name text;
BEGIN
  BEGIN
    v_token := current_setting('request.headers', true)::json->>'x-engineer-token';
  EXCEPTION WHEN OTHERS THEN RETURN NULL; END;
  IF v_token IS NULL OR v_token = '' THEN RETURN NULL; END IF;
  SELECT name INTO v_name FROM users
  WHERE session_token = v_token
    AND role = 'engineer'
    AND active = true
    AND session_expires > extract(epoch from now())::bigint;
  RETURN v_name;
END;
$function$;

CREATE OR REPLACE FUNCTION public.my_user_id()
 RETURNS text
 LANGUAGE plpgsql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE v_id text; v_token text;
BEGIN
  IF auth.uid() IS NOT NULL THEN
    SELECT id INTO v_id FROM users WHERE auth_id = auth.uid() AND active = true LIMIT 1;
    IF v_id IS NOT NULL THEN RETURN v_id; END IF;
  END IF;
  BEGIN
    v_token := current_setting('request.headers', true)::json->>'x-engineer-token';
  EXCEPTION WHEN OTHERS THEN v_token := NULL; END;
  IF v_token IS NOT NULL AND v_token <> '' THEN
    SELECT id INTO v_id FROM users
    WHERE session_token = v_token AND role = 'engineer' AND active = true
      AND session_expires > extract(epoch from now())::bigint
    LIMIT 1;
  END IF;
  RETURN v_id;
END;
$function$;

CREATE OR REPLACE FUNCTION public.next_agn_num()
 RETURNS integer
 LANGUAGE sql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  SELECT nextval('agn_num_seq')::int;
$function$;

CREATE OR REPLACE FUNCTION public.next_cr_num()
 RETURNS integer
 LANGUAGE sql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  SELECT nextval('job_cr_seq')::int;
$function$;

CREATE OR REPLACE FUNCTION public.next_inv_num()
 RETURNS integer
 LANGUAGE sql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  SELECT nextval('inv_num_seq')::int;
$function$;

CREATE OR REPLACE FUNCTION public.next_job_num()
 RETURNS integer
 LANGUAGE sql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  SELECT nextval('job_num_seq')::int;
$function$;

CREATE OR REPLACE FUNCTION public.next_proforma_num()
 RETURNS integer
 LANGUAGE sql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  SELECT nextval('proforma_num_seq')::int;
$function$;

CREATE OR REPLACE FUNCTION public.portal_get_agency(p_id text)
 RETURNS SETOF agencies
 LANGUAGE sql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  SELECT * FROM agencies WHERE id::text = p_id;
$function$;

CREATE OR REPLACE FUNCTION public.portal_get_agency_agents(p_agency_id text)
 RETURNS SETOF agents
 LANGUAGE sql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  SELECT * FROM agents WHERE agencyid::text = p_agency_id ORDER BY name ASC;
$function$;

CREATE OR REPLACE FUNCTION public.portal_get_attachments(p_job_ids text[])
 RETURNS SETOF attachments
 LANGUAGE sql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  SELECT * FROM attachments WHERE jobid::text = ANY(p_job_ids);
$function$;

CREATE OR REPLACE FUNCTION public.portal_get_certs(p_job_ids text[])
 RETURNS SETOF certs
 LANGUAGE sql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  SELECT * FROM certs WHERE jobid::text = ANY(p_job_ids);
$function$;

CREATE OR REPLACE FUNCTION public.portal_get_invoices(p_type text, p_id text)
 RETURNS SETOF invoices
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE v_name text; v_email text;
BEGIN
  IF p_type = 'landlord' THEN
    SELECT name INTO v_name FROM persons WHERE id::text = p_id;
    RETURN QUERY SELECT * FROM invoices
      WHERE client_person_id::text = p_id
         OR (v_name IS NOT NULL AND (lower(clientname) = lower(v_name) OR lower(landlordname) = lower(v_name) OR lower(billtoname) = lower(v_name)))
      ORDER BY created DESC;
  ELSIF p_type = 'agency' THEN
    SELECT name INTO v_name FROM agencies WHERE id::text = p_id;
    RETURN QUERY SELECT * FROM invoices
      WHERE client_agency_id::text = p_id
         OR (v_name IS NOT NULL AND (lower(clientname) = lower(v_name) OR lower(agencyname) = lower(v_name) OR lower(billtoname) = lower(v_name)))
      ORDER BY created DESC;
  ELSIF p_type = 'agent' THEN
    SELECT name, email INTO v_name, v_email FROM agents WHERE id::text = p_id;
    IF v_name IS NOT NULL THEN
      RETURN QUERY SELECT * FROM invoices
        WHERE lower(agentname) = lower(v_name) OR (v_email IS NOT NULL AND lower(agentemail) = lower(v_email)) OR lower(billtoname) = lower(v_name)
        ORDER BY created DESC;
    END IF;
  END IF;
END;
$function$;

CREATE OR REPLACE FUNCTION public.portal_get_jobs(p_type text, p_id text)
 RETURNS SETOF jobs
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE v_name text; v_email text;
BEGIN
  IF p_type = 'landlord' THEN
    SELECT name INTO v_name FROM persons WHERE id::text = p_id;
    RETURN QUERY SELECT * FROM jobs
      WHERE client_person_id::text = p_id
         OR (v_name IS NOT NULL AND lower(landlordname) = lower(v_name))
      ORDER BY date DESC;
  ELSIF p_type = 'agency' THEN
    SELECT name INTO v_name FROM agencies WHERE id::text = p_id;
    RETURN QUERY SELECT * FROM jobs
      WHERE client_agency_id::text = p_id
         OR (v_name IS NOT NULL AND lower(agencyname) = lower(v_name))
      ORDER BY date DESC;
  ELSIF p_type = 'agent' THEN
    SELECT name, email INTO v_name, v_email FROM agents WHERE id::text = p_id;
    IF v_name IS NOT NULL THEN
      RETURN QUERY SELECT * FROM jobs
        WHERE lower(agentname) = lower(v_name) OR (v_email IS NOT NULL AND lower(agentemail) = lower(v_email))
        ORDER BY date DESC;
    END IF;
  END IF;
END;
$function$;

CREATE OR REPLACE FUNCTION public.portal_get_person(p_id text)
 RETURNS SETOF persons
 LANGUAGE sql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  SELECT * FROM persons WHERE id::text = p_id;
$function$;

CREATE OR REPLACE FUNCTION public.portal_get_requests(p_name text)
 RETURNS SETOF engineer_requests
 LANGUAGE sql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  SELECT * FROM engineer_requests
  WHERE engineer_name ILIKE '%'||p_name||'%' AND type = 'portal_request'
  ORDER BY created DESC LIMIT 50;
$function$;

CREATE OR REPLACE FUNCTION public.portal_next_request_ref()
 RETURNS text
 LANGUAGE sql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  SELECT 'CR-'||lpad(nextval('portal_request_seq')::text, 4, '0');
$function$;

CREATE OR REPLACE FUNCTION public.portal_pin_reset(p_table text, p_id text)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
BEGIN
  IF p_table NOT IN ('persons','agencies','agents') THEN
    RAISE EXCEPTION 'Invalid table: %', p_table;
  END IF;
  EXECUTE format('UPDATE %I SET portal_pin_hash = NULL, portal_pin_fail_count = 0, portal_pin_locked_until = NULL WHERE id = $1', p_table) USING p_id;
END;
$function$;

CREATE OR REPLACE FUNCTION public.portal_pin_set(p_table text, p_id text, p_pin text)
 RETURNS boolean
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public', 'extensions'
AS $function$
DECLARE existing text;
BEGIN
  IF p_table NOT IN ('persons','agencies','agents') THEN
    RAISE EXCEPTION 'Invalid table: %', p_table;
  END IF;
  IF p_pin !~ '^[0-9]{6}$' THEN
    RAISE EXCEPTION 'PIN must be exactly 6 digits';
  END IF;
  EXECUTE format('SELECT portal_pin_hash FROM %I WHERE id = $1', p_table) INTO existing USING p_id;
  IF existing IS NOT NULL THEN
    RAISE EXCEPTION 'A PIN is already set for this account';
  END IF;
  EXECUTE format(
    'UPDATE %I SET portal_pin_hash = crypt($1, gen_salt(''bf'')), portal_pin_fail_count = 0, portal_pin_locked_until = NULL WHERE id = $2',
    p_table
  ) USING p_pin, p_id;
  RETURN true;
END;
$function$;

CREATE OR REPLACE FUNCTION public.portal_pin_status(p_table text, p_id text)
 RETURNS TABLE(has_pin boolean, locked_until timestamp with time zone)
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
BEGIN
  IF p_table NOT IN ('persons','agencies','agents') THEN
    RAISE EXCEPTION 'Invalid table: %', p_table;
  END IF;
  RETURN QUERY EXECUTE format(
    'SELECT portal_pin_hash IS NOT NULL, portal_pin_locked_until FROM %I WHERE id = $1', p_table
  ) USING p_id;
END;
$function$;

CREATE OR REPLACE FUNCTION public.portal_pin_verify(p_table text, p_id text, p_pin text)
 RETURNS boolean
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public', 'extensions'
AS $function$
DECLARE stored text; fails int; lockedUntil timestamptz; ok boolean;
BEGIN
  IF p_table NOT IN ('persons','agencies','agents') THEN
    RAISE EXCEPTION 'Invalid table: %', p_table;
  END IF;
  EXECUTE format('SELECT portal_pin_hash, portal_pin_fail_count, portal_pin_locked_until FROM %I WHERE id = $1', p_table)
    INTO stored, fails, lockedUntil USING p_id;

  IF stored IS NULL THEN RETURN false; END IF;
  IF lockedUntil IS NOT NULL AND lockedUntil > now() THEN RETURN false; END IF;

  ok := (crypt(p_pin, stored) = stored);

  IF ok THEN
    EXECUTE format('UPDATE %I SET portal_pin_fail_count = 0, portal_pin_locked_until = NULL WHERE id = $1', p_table) USING p_id;
  ELSE
    fails := COALESCE(fails,0) + 1;
    IF fails >= 5 THEN
      EXECUTE format('UPDATE %I SET portal_pin_fail_count = $1, portal_pin_locked_until = now() + interval ''15 minutes'' WHERE id = $2', p_table) USING fails, p_id;
    ELSE
      EXECUTE format('UPDATE %I SET portal_pin_fail_count = $1 WHERE id = $2', p_table) USING fails, p_id;
    END IF;
  END IF;

  RETURN ok;
END;
$function$;

CREATE OR REPLACE FUNCTION public.portal_push_subscribe(p_table text, p_id text, p_endpoint text, p_p256dh text, p_auth text)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
BEGIN
  IF p_table NOT IN ('persons','agencies','agents') THEN
    RAISE EXCEPTION 'Invalid table: %', p_table;
  END IF;
  INSERT INTO push_subscriptions(entity_table, entity_id, endpoint, p256dh, auth)
  VALUES (p_table, p_id, p_endpoint, p_p256dh, p_auth)
  ON CONFLICT (endpoint) DO UPDATE SET entity_table=EXCLUDED.entity_table, entity_id=EXCLUDED.entity_id, p256dh=EXCLUDED.p256dh, auth=EXCLUDED.auth;
END;
$function$;

CREATE OR REPLACE FUNCTION public.portal_push_unsubscribe(p_endpoint text)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
BEGIN
  DELETE FROM push_subscriptions WHERE endpoint = p_endpoint;
END;
$function$;

CREATE OR REPLACE FUNCTION public.staff_push_subscribe(p_endpoint text, p_p256dh text, p_auth text)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE v_uid text;
BEGIN
  v_uid := my_user_id();
  IF v_uid IS NULL THEN RAISE EXCEPTION 'Not authorized'; END IF;
  INSERT INTO push_subscriptions(entity_table, entity_id, endpoint, p256dh, auth)
  VALUES ('users', v_uid, p_endpoint, p_p256dh, p_auth)
  ON CONFLICT (endpoint) DO UPDATE SET entity_table=EXCLUDED.entity_table, entity_id=EXCLUDED.entity_id, p256dh=EXCLUDED.p256dh, auth=EXCLUDED.auth;
END;
$function$;

CREATE OR REPLACE FUNCTION public.staff_push_unsubscribe(p_endpoint text)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE v_uid text;
BEGIN
  v_uid := my_user_id();
  IF v_uid IS NULL THEN RAISE EXCEPTION 'Not authorized'; END IF;
  DELETE FROM push_subscriptions WHERE endpoint = p_endpoint AND entity_table = 'users' AND entity_id = v_uid;
END;
$function$;

CREATE OR REPLACE FUNCTION public.valid_invoice_items(items jsonb)
 RETURNS boolean
 LANGUAGE plpgsql
 IMMUTABLE
 SET search_path TO 'public'
AS $function$
DECLARE
  item jsonb;
  q numeric;
  u numeric;
BEGIN
  IF items IS NULL OR jsonb_typeof(items) <> 'array' THEN
    RETURN true; -- unrecognized shape isn't this constraint's concern
  END IF;
  FOR item IN SELECT * FROM jsonb_array_elements(items) LOOP
    BEGIN
      q := (item->>'qty')::numeric;
      u := (item->>'unit')::numeric;
    EXCEPTION WHEN OTHERS THEN
      CONTINUE; -- non-numeric/missing fields aren't this constraint's concern
    END;
    IF q < 0 OR u < 0 THEN
      RETURN false;
    END IF;
  END LOOP;
  RETURN true;
END;
$function$;

CREATE OR REPLACE FUNCTION public.verify_engineer_login(p_email text, p_hash text)
 RETURNS json
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
  v_user    users%ROWTYPE;
  v_token   text;
  v_expires bigint;
  v_result  json;
BEGIN
  SELECT * INTO v_user
  FROM users
  WHERE lower(trim(email)) = lower(trim(p_email))
    AND role = 'engineer'
    AND active = true
  LIMIT 1;

  IF NOT FOUND THEN RETURN NULL; END IF;

  IF v_user.pin IS NULL OR length(v_user.pin) < 64 THEN
    RETURN json_build_object('error','no_hash','name',v_user.name);
  END IF;

  IF left(v_user.pin, 64) != p_hash THEN
    RETURN NULL;
  END IF;

  -- Use md5+random instead of gen_random_bytes to avoid pgcrypto issues
  v_token   := md5(random()::text || clock_timestamp()::text || v_user.id::text);
  v_expires := extract(epoch from now())::bigint + (30 * 24 * 60 * 60);

  UPDATE users
  SET session_token = v_token, session_expires = v_expires,
      last_seen = extract(epoch from now())::bigint
  WHERE id = v_user.id;

  SELECT json_build_object(
    'id', v_user.id, 'name', v_user.name, 'email', v_user.email,
    'phone', v_user.phone, 'role', v_user.role, 'active', true,
    'session_token', v_token, 'session_expires', v_expires,
    'see_landlord', v_user.see_landlord,
    'see_landlord_phone', v_user.see_landlord_phone,
    'see_agent', v_user.see_agent,
    'see_contact', v_user.see_contact,
    'see_price', v_user.see_price
  ) INTO v_result;

  RETURN v_result;
END;
$function$;


-- ============================================================================
-- SECTION 7 — CONSTRAINT ADDED POST-FUNCTION (invoices.items)
-- ============================================================================
-- Deferred from Section 3: valid_invoice_items() must exist before a CHECK
-- constraint can call it. Rejects negative qty/unit values on line items;
-- everything else about invoices.items' shape is enforced by convention
-- only (see docs/architecture/05-database.md §5 for the real element shape).

ALTER TABLE public.invoices
  ADD CONSTRAINT invoices_items_no_negative_values CHECK (valid_invoice_items(items));


-- ============================================================================
-- SECTION 8 — TRIGGERS
-- ============================================================================
-- Exactly one custom trigger exists anywhere in this project (confirmed via
-- pg_trigger, excluding Supabase's own built-in storage/realtime triggers,
-- which every fresh project already has and which this file doesn't need to
-- recreate). It fires on auth.users, not a public-schema table — disaster-
-- recovery path that recreates the primary admin's public.users profile if
-- it's ever missing. Applying this statement requires privileges on the
-- `auth` schema (see the file-level note at the top of this file).

CREATE TRIGGER trg_auto_admin
  AFTER INSERT ON auth.users
  FOR EACH ROW
  EXECUTE FUNCTION public.auto_create_admin_profile();


-- ============================================================================
-- SECTION 9 — ROW LEVEL SECURITY: ENABLE + POLICIES
-- ============================================================================
-- RLS is enabled on all 21 tables (confirmed live via pg_class.relrowsecurity
-- — relforcerowsecurity is false everywhere too, i.e. table owners/
-- superusers still bypass RLS as normal). `push_subscriptions` has RLS
-- enabled with ZERO policies, deliberately — see the comment above its
-- ENABLE statement. Every policy below is transcribed verbatim from
-- pg_policies (qual/with_check expressions, roles, cmd) — 41 policies
-- across 20 tables.

ALTER TABLE public.persons ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.agencies ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.agents ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.jobs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.certs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.invoices ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.job_comments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.attachments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.activity ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.engineer_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.engineer_alerts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.app_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.payments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cert_reminder_log ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.expenses ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.overtime ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.audit_log ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.portal_contacts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.invoice_audit ENABLE ROW LEVEL SECURITY;
-- push_subscriptions: RLS enabled, no policies below — by design (Web Push
-- credentials; unreachable via anon/authenticated REST, written only
-- through the SECURITY DEFINER RPCs in Section 6, which run as their
-- owner and so aren't subject to RLS themselves).
ALTER TABLE public.push_subscriptions ENABLE ROW LEVEL SECURITY;

-- ---------------------------------------------------------------------------
-- activity
-- ---------------------------------------------------------------------------
CREATE POLICY activity_client_requests ON public.activity FOR INSERT TO anon
  WITH CHECK (type = 'client_request'::text);
CREATE POLICY activity_office_all ON public.activity FOR ALL TO authenticated
  USING (is_office()) WITH CHECK (is_office());

-- ---------------------------------------------------------------------------
-- agencies
-- ---------------------------------------------------------------------------
CREATE POLICY agencies_office_only ON public.agencies FOR ALL TO authenticated
  USING (is_office()) WITH CHECK (is_office());

-- ---------------------------------------------------------------------------
-- agents
-- ---------------------------------------------------------------------------
CREATE POLICY agents_office_only ON public.agents FOR ALL TO authenticated
  USING (is_office()) WITH CHECK (is_office());

-- ---------------------------------------------------------------------------
-- app_settings
-- ---------------------------------------------------------------------------
CREATE POLICY portal_settings_read ON public.app_settings FOR SELECT TO anon
  USING (key = '__all__'::text);
CREATE POLICY settings_office_only ON public.app_settings FOR ALL TO authenticated
  USING (is_office()) WITH CHECK (is_office());

-- ---------------------------------------------------------------------------
-- attachments
-- ---------------------------------------------------------------------------
CREATE POLICY attachments_engineer_own ON public.attachments FOR ALL TO authenticated
  USING (is_engineer() AND (jobid IN (SELECT jobs.id FROM jobs WHERE jobs.engineer = my_engineer_name())))
  WITH CHECK (is_engineer() AND (jobid IN (SELECT jobs.id FROM jobs WHERE jobs.engineer = my_engineer_name())));
CREATE POLICY attachments_engineer_token ON public.attachments FOR ALL TO public
  USING (is_valid_engineer_token() AND (jobid IN (SELECT jobs.id FROM jobs WHERE jobs.engineer = my_token_engineer_name())))
  WITH CHECK (is_valid_engineer_token() AND (jobid IN (SELECT jobs.id FROM jobs WHERE jobs.engineer = my_token_engineer_name())));
CREATE POLICY attachments_office_all ON public.attachments FOR ALL TO authenticated
  USING (is_office()) WITH CHECK (is_office());

-- ---------------------------------------------------------------------------
-- audit_log
-- ---------------------------------------------------------------------------
CREATE POLICY audit_log_office_only ON public.audit_log FOR ALL TO authenticated
  USING (is_office()) WITH CHECK (is_office());

-- ---------------------------------------------------------------------------
-- cert_reminder_log
-- ---------------------------------------------------------------------------
CREATE POLICY cert_reminder_log_office_all ON public.cert_reminder_log FOR ALL TO authenticated
  USING (is_office()) WITH CHECK (is_office());

-- ---------------------------------------------------------------------------
-- certs
-- ---------------------------------------------------------------------------
CREATE POLICY certs_engineer_read ON public.certs FOR SELECT TO authenticated
  USING (is_engineer());
CREATE POLICY certs_engineer_token_read ON public.certs FOR SELECT TO public
  USING (is_valid_engineer_token());
CREATE POLICY certs_office_all ON public.certs FOR ALL TO authenticated
  USING (is_office()) WITH CHECK (is_office());

-- ---------------------------------------------------------------------------
-- engineer_alerts
-- ---------------------------------------------------------------------------
CREATE POLICY engineer_alerts_office_all ON public.engineer_alerts FOR ALL TO authenticated
  USING (is_office()) WITH CHECK (is_office());
CREATE POLICY engineer_alerts_token ON public.engineer_alerts FOR ALL TO public
  USING (is_valid_engineer_token()) WITH CHECK (is_valid_engineer_token());

-- ---------------------------------------------------------------------------
-- engineer_requests
-- ---------------------------------------------------------------------------
CREATE POLICY eng_requests_engineer_own ON public.engineer_requests FOR ALL TO authenticated
  USING (is_engineer() AND (engineer_name = my_engineer_name()))
  WITH CHECK (is_engineer() AND (engineer_name = my_engineer_name()));
CREATE POLICY eng_requests_engineer_token ON public.engineer_requests FOR ALL TO public
  USING (is_valid_engineer_token() AND (engineer_name = my_token_engineer_name()))
  WITH CHECK (is_valid_engineer_token() AND (engineer_name = my_token_engineer_name()));
CREATE POLICY eng_requests_office_all ON public.engineer_requests FOR ALL TO authenticated
  USING (is_office()) WITH CHECK (is_office());
CREATE POLICY portal_requests_insert ON public.engineer_requests FOR INSERT TO anon
  WITH CHECK (type = 'portal_request'::text);

-- ---------------------------------------------------------------------------
-- expenses
-- ---------------------------------------------------------------------------
CREATE POLICY expenses_office_only ON public.expenses FOR ALL TO authenticated
  USING (is_office()) WITH CHECK (is_office());

-- ---------------------------------------------------------------------------
-- invoice_audit
-- ---------------------------------------------------------------------------
CREATE POLICY invoice_audit_office_insert ON public.invoice_audit FOR INSERT TO authenticated
  WITH CHECK (is_office());
CREATE POLICY invoice_audit_office_read ON public.invoice_audit FOR SELECT TO authenticated
  USING (is_office());

-- ---------------------------------------------------------------------------
-- invoices
-- ---------------------------------------------------------------------------
CREATE POLICY invoices_office_all ON public.invoices FOR ALL TO authenticated
  USING (is_office()) WITH CHECK (is_office());

-- ---------------------------------------------------------------------------
-- job_comments
-- ---------------------------------------------------------------------------
CREATE POLICY job_comments_office_only ON public.job_comments FOR ALL TO authenticated
  USING (is_office()) WITH CHECK (is_office());

-- ---------------------------------------------------------------------------
-- jobs
-- ---------------------------------------------------------------------------
CREATE POLICY jobs_engineer_own ON public.jobs FOR SELECT TO authenticated
  USING (is_engineer() AND (engineer = my_engineer_name()));
CREATE POLICY jobs_engineer_token_select ON public.jobs FOR SELECT TO public
  USING (is_valid_engineer_token() AND (engineer = my_token_engineer_name()));
CREATE POLICY jobs_engineer_token_update ON public.jobs FOR UPDATE TO public
  USING (is_valid_engineer_token() AND (engineer = my_token_engineer_name()))
  WITH CHECK (is_valid_engineer_token() AND (engineer = my_token_engineer_name()));
CREATE POLICY jobs_engineer_update_own ON public.jobs FOR UPDATE TO authenticated
  USING (is_engineer() AND (engineer = my_engineer_name()))
  WITH CHECK (is_engineer() AND (engineer = my_engineer_name()));
-- Delete requires can_delete=true (or admin/manager role) at the database
-- level, not just client-side UI enforcement.
CREATE POLICY jobs_office_delete ON public.jobs FOR DELETE TO authenticated
  USING (is_office() AND EXISTS (
    SELECT 1 FROM users WHERE users.auth_id = (SELECT auth.uid())
      AND (users.can_delete = true OR users.role = ANY (ARRAY['admin'::text,'manager'::text]))
  ));
CREATE POLICY jobs_office_insert ON public.jobs FOR INSERT TO authenticated
  WITH CHECK (is_office());
CREATE POLICY jobs_office_select ON public.jobs FOR SELECT TO authenticated
  USING (is_office());
CREATE POLICY jobs_office_update ON public.jobs FOR UPDATE TO authenticated
  USING (is_office()) WITH CHECK (is_office());

-- ---------------------------------------------------------------------------
-- overtime
-- ---------------------------------------------------------------------------
CREATE POLICY overtime_office_only ON public.overtime FOR ALL TO authenticated
  USING (is_office()) WITH CHECK (is_office());

-- ---------------------------------------------------------------------------
-- payments
-- ---------------------------------------------------------------------------
CREATE POLICY payments_office_only ON public.payments FOR ALL TO authenticated
  USING (is_office()) WITH CHECK (is_office());

-- ---------------------------------------------------------------------------
-- persons
-- ---------------------------------------------------------------------------
CREATE POLICY persons_office_only ON public.persons FOR ALL TO authenticated
  USING (is_office()) WITH CHECK (is_office());

-- ---------------------------------------------------------------------------
-- portal_contacts
-- ---------------------------------------------------------------------------
CREATE POLICY portal_contacts_office_write ON public.portal_contacts FOR ALL TO authenticated
  USING (is_office()) WITH CHECK (is_office());
CREATE POLICY portal_contacts_public_read ON public.portal_contacts FOR SELECT TO public
  USING (true);

-- ---------------------------------------------------------------------------
-- users
-- ---------------------------------------------------------------------------
CREATE POLICY users_engineer_own_read ON public.users FOR SELECT TO authenticated
  USING (is_engineer() AND (auth_id = (SELECT auth.uid())));
CREATE POLICY users_engineer_token_own_read ON public.users FOR SELECT TO public
  USING (is_valid_engineer_token() AND (session_token = ((SELECT current_setting('request.headers'::text, true))::json ->> 'x-engineer-token'::text)));
CREATE POLICY users_office_all ON public.users FOR ALL TO authenticated
  USING (is_office()) WITH CHECK (is_office());


-- ============================================================================
-- SECTION 10 — DEFAULT PRIVILEGES / GRANTS
-- ============================================================================
-- Confirmed live via pg_default_acl: this project already has a per-role
-- default-privilege baseline (owner postgres, schema public) that
-- auto-grants ALL on new tables, rwU (SELECT/UPDATE/USAGE) on new
-- sequences, and EXECUTE on new functions, to anon/authenticated/
-- service_role — this is standard Supabase project bootstrapping, present
-- on every fresh project before any migration ever runs, which is exactly
-- why almost none of the 41 functions above needed an explicit GRANT
-- statement to be callable by anon/authenticated. The block below makes
-- that assumption explicit and self-sufficient rather than silently relying
-- on it, then the REVOKEs beneath it narrow the ~15 functions whose live
-- grants are less permissive than that default.

GRANT USAGE ON SCHEMA public TO anon, authenticated, service_role;
GRANT ALL ON ALL TABLES IN SCHEMA public TO anon, authenticated, service_role;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated, service_role;
GRANT ALL ON ALL FUNCTIONS IN SCHEMA public TO anon, authenticated, service_role;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO anon, authenticated, service_role;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO anon, authenticated, service_role;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT EXECUTE ON FUNCTIONS TO anon, authenticated, service_role;

-- Four functions have NO anon/authenticated EXECUTE grant live — postgres/
-- service_role (migrations, Edge Functions using the service key) only.
-- admin_set_seq: raw sequence-position surgery, dangerous if public.
-- auto_create_admin_profile: trigger function only, never meant to be
--   called directly. create_confirmed_user: creates a real auth.users row
--   bypassing normal signup — admin/service-role tooling only.
-- verify_engineer_login: dead — references a `pin` column dropped from
--   `users` (superseded by pin_hash); revoked live by
--   20260725163831_h1_revoke_dead_verify_engineer_login_rpc.sql; kept here
--   verbatim per this file's own header note, not re-enabled.
REVOKE ALL ON FUNCTION public.admin_set_seq(text, integer) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.auto_create_admin_profile() FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.create_confirmed_user(text, text) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.verify_engineer_login(text, text) FROM PUBLIC, anon, authenticated;

-- Eleven functions are authenticated-only live (office-side utilities and
-- admin actions that anon — an unauthenticated Portal/public visitor —
-- should never be able to invoke, even though the schema default would
-- otherwise grant it EXECUTE too).
REVOKE EXECUTE ON FUNCTION public.check_cert_reminder_setup() FROM anon;
REVOKE EXECUTE ON FUNCTION public.engineer_allow_pin_reset(text, boolean) FROM anon;
REVOKE EXECUTE ON FUNCTION public.engineer_pin_clear(text, boolean) FROM anon;
REVOKE EXECUTE ON FUNCTION public.engineer_pin_set(text, text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_auth_users() FROM anon;
REVOKE EXECUTE ON FUNCTION public.next_agn_num() FROM anon;
REVOKE EXECUTE ON FUNCTION public.next_cr_num() FROM anon;
REVOKE EXECUTE ON FUNCTION public.next_inv_num() FROM anon;
REVOKE EXECUTE ON FUNCTION public.next_job_num() FROM anon;
REVOKE EXECUTE ON FUNCTION public.next_proforma_num() FROM anon;
REVOKE EXECUTE ON FUNCTION public.portal_pin_reset(text, text) FROM anon;

-- The remaining 26 functions (engineer_pin_login, engineer_pin_self_setup,
-- engineer_session_logout, is_engineer, is_office, is_valid_engineer_token,
-- my_engineer_name, my_token_engineer_name, my_user_id, portal_get_agency,
-- portal_get_agency_agents, portal_get_attachments, portal_get_certs,
-- portal_get_invoices, portal_get_jobs, portal_get_person,
-- portal_get_requests, portal_next_request_ref, portal_pin_set,
-- portal_pin_status, portal_pin_verify, portal_push_subscribe,
-- portal_push_unsubscribe, staff_push_subscribe, staff_push_unsubscribe,
-- valid_invoice_items) keep the schema default: EXECUTE for both anon and
-- authenticated. No further action needed for those.


-- ============================================================================
-- SECTION 11 — REALTIME
-- ============================================================================
-- Matches 20260720100129_add_jobs_to_realtime_publication.sql exactly.
-- `supabase_realtime` itself is a publication every Supabase project
-- creates automatically at provisioning time (not public-schema DDL); this
-- just adds `jobs` to it, the only table in this schema wired up for
-- Realtime row-change streaming.

ALTER PUBLICATION supabase_realtime ADD TABLE public.jobs;

-- ============================================================================
-- END 0000_initial_schema.sql
-- ============================================================================
